[2024-03-31 14:54:15,206: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2024-03-31 14:54:15,348: DEBUG/MainProcess] | Worker: Building graph...
[2024-03-31 14:54:15,350: DEBUG/MainProcess] | Worker: New boot order: {StateDB, Beat, Timer, Hub, Pool, Autoscaler, Consumer}
[2024-03-31 14:54:15,373: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2024-03-31 14:54:15,374: DEBUG/MainProcess] | Consumer: Building graph...
[2024-03-31 14:54:15,417: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Mingle, Gossip, Heart, Agent, Tasks, Control, event loop}
[2024-03-31 14:54:15,455: DEBUG/MainProcess] | Worker: Starting Hub
[2024-03-31 14:54:15,455: DEBUG/MainProcess] ^-- substep ok
[2024-03-31 14:54:15,456: DEBUG/MainProcess] | Worker: Starting Pool
[2024-03-31 14:54:16,781: DEBUG/MainProcess] ^-- substep ok
[2024-03-31 14:54:16,785: DEBUG/MainProcess] | Worker: Starting Consumer
[2024-03-31 14:54:16,788: DEBUG/MainProcess] | Consumer: Starting Connection
[2024-03-31 14:54:16,815: WARNING/MainProcess] /home/al-areef/Codes/SyncWrite/sync_venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-03-31 14:54:16,859: INFO/MainProcess] Connected to redis://localhost:6379/0
[2024-03-31 14:54:16,860: DEBUG/MainProcess] ^-- substep ok
[2024-03-31 14:54:16,861: DEBUG/MainProcess] | Consumer: Starting Events
[2024-03-31 14:54:16,865: WARNING/MainProcess] /home/al-areef/Codes/SyncWrite/sync_venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-03-31 14:54:16,876: DEBUG/MainProcess] ^-- substep ok
[2024-03-31 14:54:16,877: DEBUG/MainProcess] | Consumer: Starting Mingle
[2024-03-31 14:54:16,878: INFO/MainProcess] mingle: searching for neighbors
[2024-03-31 14:54:17,930: INFO/MainProcess] mingle: all alone
[2024-03-31 14:54:17,931: DEBUG/MainProcess] ^-- substep ok
[2024-03-31 14:54:17,932: DEBUG/MainProcess] | Consumer: Starting Gossip
[2024-03-31 14:54:17,954: DEBUG/MainProcess] ^-- substep ok
[2024-03-31 14:54:17,955: DEBUG/MainProcess] | Consumer: Starting Heart
[2024-03-31 14:54:17,968: DEBUG/MainProcess] ^-- substep ok
[2024-03-31 14:54:17,969: DEBUG/MainProcess] | Consumer: Starting Tasks
[2024-03-31 14:54:18,006: DEBUG/MainProcess] ^-- substep ok
[2024-03-31 14:54:18,007: DEBUG/MainProcess] | Consumer: Starting Control
[2024-03-31 14:54:18,061: DEBUG/MainProcess] ^-- substep ok
[2024-03-31 14:54:18,063: DEBUG/MainProcess] | Consumer: Starting event loop
[2024-03-31 14:54:18,064: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2024-03-31 14:54:18,067: INFO/MainProcess] celery@al-areef ready.
[2024-03-31 14:54:18,069: DEBUG/MainProcess] basic.qos: prefetch_count->16
[2024-03-31 14:55:50,874: DEBUG/MainProcess] | Worker: Closing Hub...
[2024-03-31 14:55:50,874: DEBUG/MainProcess] | Worker: Closing Pool...
[2024-03-31 14:55:50,875: DEBUG/MainProcess] | Worker: Closing Consumer...
[2024-03-31 14:55:50,876: DEBUG/MainProcess] | Worker: Stopping Consumer...
[2024-03-31 14:55:50,876: DEBUG/MainProcess] | Consumer: Closing Connection...
[2024-03-31 14:55:50,877: DEBUG/MainProcess] | Consumer: Closing Events...
[2024-03-31 14:55:50,877: DEBUG/MainProcess] | Consumer: Closing Mingle...
[2024-03-31 14:55:50,878: DEBUG/MainProcess] | Consumer: Closing Gossip...
[2024-03-31 14:55:50,878: DEBUG/MainProcess] | Consumer: Closing Heart...
[2024-03-31 14:55:50,879: DEBUG/MainProcess] | Consumer: Closing Tasks...
[2024-03-31 14:55:50,879: DEBUG/MainProcess] | Consumer: Closing Control...
[2024-03-31 14:55:50,880: DEBUG/MainProcess] | Consumer: Closing event loop...
[2024-03-31 14:55:50,880: DEBUG/MainProcess] | Consumer: Stopping event loop...
[2024-03-31 14:55:50,880: DEBUG/MainProcess] | Consumer: Stopping Control...
[2024-03-31 14:55:50,908: DEBUG/MainProcess] | Consumer: Stopping Tasks...
[2024-03-31 14:55:50,909: DEBUG/MainProcess] Canceling task consumer...
[2024-03-31 14:55:50,910: DEBUG/MainProcess] | Consumer: Stopping Heart...
[2024-03-31 14:55:50,915: DEBUG/MainProcess] | Consumer: Stopping Gossip...
[2024-03-31 14:55:50,948: DEBUG/MainProcess] | Consumer: Stopping Mingle...
[2024-03-31 14:55:50,948: DEBUG/MainProcess] | Consumer: Stopping Events...
[2024-03-31 14:55:50,949: DEBUG/MainProcess] | Consumer: Stopping Connection...
[2024-03-31 14:55:50,949: DEBUG/MainProcess] | Worker: Stopping Pool...
[2024-03-31 14:55:52,048: DEBUG/MainProcess] | Worker: Stopping Hub...
[2024-03-31 14:55:52,049: DEBUG/MainProcess] | Consumer: Shutdown Control...
[2024-03-31 14:55:52,050: DEBUG/MainProcess] | Consumer: Shutdown Tasks...
[2024-03-31 14:55:52,051: DEBUG/MainProcess] Canceling task consumer...
[2024-03-31 14:55:52,052: DEBUG/MainProcess] Closing consumer channel...
[2024-03-31 14:55:52,053: DEBUG/MainProcess] | Consumer: Shutdown Heart...
[2024-03-31 14:55:52,056: DEBUG/MainProcess] | Consumer: Shutdown Gossip...
[2024-03-31 14:55:52,058: DEBUG/MainProcess] | Consumer: Shutdown Events...
[2024-03-31 14:55:52,060: DEBUG/MainProcess] | Consumer: Shutdown Connection...
[2024-03-31 14:55:52,070: DEBUG/MainProcess] removing tasks from inqueue until task handler finished
[2024-03-31 14:56:08,678: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2024-03-31 14:56:08,853: DEBUG/MainProcess] | Worker: Building graph...
[2024-03-31 14:56:08,856: DEBUG/MainProcess] | Worker: New boot order: {StateDB, Beat, Timer, Hub, Pool, Autoscaler, Consumer}
[2024-03-31 14:56:08,891: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2024-03-31 14:56:08,894: DEBUG/MainProcess] | Consumer: Building graph...
[2024-03-31 14:56:08,968: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Mingle, Tasks, Control, Gossip, Heart, Agent, event loop}
[2024-03-31 14:56:09,021: DEBUG/MainProcess] | Worker: Starting Hub
[2024-03-31 14:56:09,022: DEBUG/MainProcess] ^-- substep ok
[2024-03-31 14:56:09,022: DEBUG/MainProcess] | Worker: Starting Pool
[2024-03-31 14:56:10,034: DEBUG/MainProcess] ^-- substep ok
[2024-03-31 14:56:10,037: DEBUG/MainProcess] | Worker: Starting Consumer
[2024-03-31 14:56:10,040: DEBUG/MainProcess] | Consumer: Starting Connection
[2024-03-31 14:56:10,049: WARNING/MainProcess] /home/al-areef/Codes/SyncWrite/sync_venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-03-31 14:56:10,084: INFO/MainProcess] Connected to redis://localhost:6379/0
[2024-03-31 14:56:10,085: DEBUG/MainProcess] ^-- substep ok
[2024-03-31 14:56:10,085: DEBUG/MainProcess] | Consumer: Starting Events
[2024-03-31 14:56:10,089: WARNING/MainProcess] /home/al-areef/Codes/SyncWrite/sync_venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-03-31 14:56:10,100: DEBUG/MainProcess] ^-- substep ok
[2024-03-31 14:56:10,101: DEBUG/MainProcess] | Consumer: Starting Mingle
[2024-03-31 14:56:10,102: INFO/MainProcess] mingle: searching for neighbors
[2024-03-31 14:56:11,154: INFO/MainProcess] mingle: all alone
[2024-03-31 14:56:11,155: DEBUG/MainProcess] ^-- substep ok
[2024-03-31 14:56:11,155: DEBUG/MainProcess] | Consumer: Starting Tasks
[2024-03-31 14:56:11,171: DEBUG/MainProcess] ^-- substep ok
[2024-03-31 14:56:11,172: DEBUG/MainProcess] | Consumer: Starting Control
[2024-03-31 14:56:11,187: DEBUG/MainProcess] ^-- substep ok
[2024-03-31 14:56:11,187: DEBUG/MainProcess] | Consumer: Starting Gossip
[2024-03-31 14:56:11,206: DEBUG/MainProcess] ^-- substep ok
[2024-03-31 14:56:11,207: DEBUG/MainProcess] | Consumer: Starting Heart
[2024-03-31 14:56:11,216: DEBUG/MainProcess] ^-- substep ok
[2024-03-31 14:56:11,217: DEBUG/MainProcess] | Consumer: Starting event loop
[2024-03-31 14:56:11,218: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2024-03-31 14:56:11,221: INFO/MainProcess] celery@al-areef ready.
[2024-03-31 14:56:11,222: DEBUG/MainProcess] basic.qos: prefetch_count->16
[2024-03-31 21:40:29,545: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2024-03-31 21:40:30,303: DEBUG/MainProcess] | Worker: Building graph...
[2024-03-31 21:40:30,305: DEBUG/MainProcess] | Worker: New boot order: {Beat, StateDB, Timer, Hub, Pool, Autoscaler, Consumer}
[2024-03-31 21:40:30,560: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2024-03-31 21:40:30,562: DEBUG/MainProcess] | Consumer: Building graph...
[2024-03-31 21:40:30,861: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Mingle, Gossip, Tasks, Control, Agent, Heart, event loop}
[2024-03-31 21:40:31,229: DEBUG/MainProcess] | Worker: Starting Hub
[2024-03-31 21:40:31,230: DEBUG/MainProcess] ^-- substep ok
[2024-03-31 21:40:31,230: DEBUG/MainProcess] | Worker: Starting Pool
[2024-03-31 21:40:34,236: DEBUG/MainProcess] ^-- substep ok
[2024-03-31 21:40:34,239: DEBUG/MainProcess] | Worker: Starting Consumer
[2024-03-31 21:40:34,242: DEBUG/MainProcess] | Consumer: Starting Connection
[2024-03-31 21:40:34,330: WARNING/MainProcess] /home/al-areef/Codes/SyncWrite/sync_venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-03-31 21:40:34,360: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

[2024-03-31 21:40:36,369: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 4.00 seconds... (2/100)

[2024-03-31 21:40:40,380: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 6.00 seconds... (3/100)

[2024-03-31 21:40:46,397: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 8.00 seconds... (4/100)

[2024-03-31 21:40:54,411: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 10.00 seconds... (5/100)

[2024-03-31 21:41:04,427: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 12.00 seconds... (6/100)

[2024-03-31 21:41:16,444: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 14.00 seconds... (7/100)

[2024-03-31 21:41:30,461: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 16.00 seconds... (8/100)

[2024-03-31 21:41:46,492: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 18.00 seconds... (9/100)

[2024-03-31 21:42:04,516: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 20.00 seconds... (10/100)

[2024-03-31 21:42:24,541: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 22.00 seconds... (11/100)

[2024-03-31 21:42:46,568: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 24.00 seconds... (12/100)

[2024-03-31 21:43:10,608: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 26.00 seconds... (13/100)

[2024-03-31 21:43:36,640: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 28.00 seconds... (14/100)

[2024-03-31 21:44:04,671: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 30.00 seconds... (15/100)

[2024-03-31 21:44:34,711: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:45:06,758: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:45:38,808: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:46:10,857: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:46:42,907: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:47:14,952: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:47:46,998: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:48:19,041: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:48:51,081: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:49:23,148: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:49:55,191: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:50:27,233: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:50:59,278: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:51:31,331: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:52:03,376: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:52:35,427: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:53:07,472: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:53:39,514: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:54:11,550: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:54:43,596: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:55:15,638: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:55:47,685: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:56:19,733: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:56:51,779: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:57:23,818: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:57:55,860: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2024-03-31 21:58:27,905: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

